@startuml advogado

left to right direction

package Advogado {
    usecase "Criar advogado" as criarAdvogado
    usecase "Editar advogado" as editarAdvogado
}

package Pergunta {
    usecase "Responder pergunta" as responderPergunta
}

package Sala {
    usecase "Criar sala" as criarSala
    usecase "Editar sala" as editarSala
    usecase "Acessar sala" as acessarSala
}

package Artigo {
    usecase "Publicar artigo" as publicarArtigo
    usecase "Pesquisar artigo" as pesquisarArtigo    
}

package Plano {
    usecase "Escolher plano" as escolherPlano
}

usecase "Gerar extrato" as gerarExtrato

actor "Advogado" as advogado

criarAdvogado -- advogado
editarAdvogado -- advogado
responderPergunta -- advogado
advogado -- criarSala
advogado -- editarSala
advogado -- acessarSala
advogado -- publicarArtigo
advogado -- pesquisarArtigo
advogado -- escolherPlano
gerarExtrato -- advogado

@enduml