@startuml cliente

left to right direction

package Cliente {
    usecase "Criar cliente" as criarCliente
    usecase "Editar cliente" as editarCliente
}

package Advogado {
    usecase "Pesquisar advogado" as pesquisarAdvogado    
}

package Pergunta {
    usecase "Realizar pergunta" as realizarPergunta
}

package Sala {
    usecase "Acessar sala" as acessarSala
}

usecase "Gerar extrato" as gerarExtrato

actor "Cliente" as cliente

criarCliente -- cliente
editarCliente -- cliente
cliente -- pesquisarAdvogado
cliente -- realizarPergunta
cliente -- acessarSala
gerarExtrato -- cliente

@enduml