@startuml gestor

left to right direction

package Cliente {
    usecase "Ativar/Inativar cliente" as ativarInativarCliente
    usecase "Excluir cliente" as excluirCliente
}

package Advogado {
    usecase "Ativar/Inativar advogado" as ativarInativarAdvogado
    usecase "Excluir advogado" as excluirAdvogado
}

package Pergunta {
    usecase "Editar pergunta" as editarPergunta
    usecase "Excluir pergunta" as excluirPergunta
    usecase "Auditar pergunta" as auditarPergunta
}

package Sala {
    usecase "Criar sala" as criarSala
    usecase "Editar sala" as editarSala
    usecase "Excluir sala" as excluirSala
}

package Artigo {
    usecase "Excluir artigo" as excluirArtigo
    usecase "Sinalizar artigo" as sinalizarArtigo
}

package Plano {
    usecase "Criar plano" as criarPlano
    usecase "Editar plano" as editarPlano
    usecase "Excluir plano" as excluirPlano
}

actor "Gestor" as gestor

ativarInativarCliente -- gestor
excluirCliente -- gestor
ativarInativarAdvogado -- gestor
excluirAdvogado -- gestor
editarPergunta -- gestor
excluirPergunta -- gestor
auditarPergunta -- gestor
gestor -- criarSala
gestor -- editarSala
gestor -- excluirSala
gestor -- excluirArtigo
gestor -- sinalizarArtigo
gestor -- criarPlano
gestor -- editarPlano
gestor -- excluirPlano

@enduml