@startuml usuario

top to bottom direction

package Sessão {
    usecase "Efetuar logon" as efetuarLogon
    usecase "Efetuar logoff" as efetuarLogoff
}

package Senha {
    usecase "Alterar senha" as alterarSenha
    usecase "Recuperar senha" as recuperarSenha    
}

actor "Usuário" as usuario
actor "Cliente" as cliente
actor "Advogado" as advogado
actor "Gestor" as gestor
actor "Estagiário" as estagiario

usuario <|-- cliente
usuario <|-- advogado
usuario <|-- gestor
usuario <|-- estagiario

efetuarLogon -- usuario
efetuarLogoff -- usuario
alterarSenha -- usuario
recuperarSenha -- usuario

@enduml